from __future__ import annotations
import json
from pathlib import Path
import pytest
import app
from scripts import build_cn_program_base_event_tier_a_report_only_holdout_authorization_v1 as auth_builder
from scripts import build_cn_program_base_event_tier_a_report_only_holdout_recovery_authorization_v1 as recovery_auth_builder
from scripts import run_cn_program_base_event_tier_a_report_only_holdout_v1 as r
from scripts import run_cn_finalist_replay_then_oos as replay
from our_system_phase2.runtime import cn_program_base_event_tier_a_report_only_holdout_v1 as runtime
from our_system_phase2.services.project_control_admission import ACTION_LAUNCH,ACTION_RETRY,CAMPAIGN_AUTHORIZATION_BOUND_ROUTES

ROOT=Path(__file__).resolve().parents[1]; PLAN=ROOT/'runtime/run_plans/cn_program_base_event_tier_a_report_only_holdout_plan.json'
def test_holdout_route_is_high_cost_and_authorization_bound():
 route=runtime.ROUTE_ID; assert app.ROUTES[route]=='our_system_phase2.runtime.cn_program_base_event_tier_a_report_only_holdout_v1'; assert app.HIGH_COST_ROUTE_ACTIONS[route]=={ACTION_LAUNCH,ACTION_RETRY}; assert route in CAMPAIGN_AUTHORIZATION_BOUND_ROUTES
def test_holdout_plan_freezes_two_mechanisms_three_fields_and_three_windows():
 p=r.verify_plan(PLAN,repo_root=ROOT); assert p['candidate_count']==2 and len(p['family_ids'])==2; assert len(p['required_physical_leaf_ids'])==3; assert p['required_physical_leaf_ids']==['ctx_hfq_volume_ratio','fund_disclosure_cashflow_pulse','fund_leverage_liabilities_assets']; assert [x['session_count'] for x in p['holdout_windows']]==[16,16,16]; assert p['holdout_windows'][0]['start_date']=='2025-10-27' and p['holdout_windows'][-1]['end_date']=='2025-12-31'; assert p['holdout_access_authorized'] is False; assert all(p[k]==0 for k in ('holdout_reads','validation_reads','historical_challenge_reads','forward_b_reads','forward_2026_reads')); assert p['promotion_authorized'] is False and p['automatic_successor_authorized'] is False
def test_holdout_endpoint_is_two_of_two_by_mechanism_not_rate_threshold():
 p=r.verify_plan(PLAN,repo_root=ROOT); assert p['endpoint_contract']['cohort_pass_count_threshold']=='EXACTLY_2_OF_2_REQUIRED_BY_MECHANISM_GEOMETRY_NOT_POST_HOC_RATE_THRESHOLD'; a,b=p['family_ids']; ok=r._metrics(p,[{'family_id':a,'exact_identity':'a','candidate_holdout_survivor':True,'holdout_productive':True,'holdout_stable_2of3':True,'cross_window_positive_increment_count':2},{'family_id':b,'exact_identity':'b','candidate_holdout_survivor':True,'holdout_productive':True,'holdout_stable_2of3':True,'cross_window_positive_increment_count':3}]); assert ok['status']==r.SUPPORTED and ok['family_support_observed']==2; fail=r._metrics(p,[{'family_id':a,'exact_identity':'a','candidate_holdout_survivor':True,'holdout_productive':True,'holdout_stable_2of3':True,'cross_window_positive_increment_count':2},{'family_id':b,'exact_identity':'b','candidate_holdout_survivor':False,'holdout_productive':False,'holdout_stable_2of3':False,'cross_window_positive_increment_count':1}]); assert fail['status']==r.NOT_SUPPORTED and fail['family_support_observed']==1
def test_holdout_builds_role_bound_context_only_inside_runner():
 src=(ROOT/'scripts/run_cn_program_base_event_tier_a_report_only_holdout_v1.py').read_text(encoding='utf-8-sig'); assert "'--evaluation-role','holdout'" in src; assert 'build_cn_phase3cm_forward_label_sidecars.py' in src; assert 'verify_cn_report_only_session_authority.py' in src; assert "data_role='holdout_report_only'" in src; assert "'promotion_authorized':False" in src
def test_holdout_label_builder_thread_environment_is_frozen():
 env=r._label_builder_env(8); expected={'NUMBA_NUM_THREADS':'1','ARROW_NUM_THREADS':'1','OMP_NUM_THREADS':'1','MKL_NUM_THREADS':'1','OPENBLAS_NUM_THREADS':'1','NUMEXPR_MAX_THREADS':'1','POLARS_MAX_THREADS':'8'}; assert {k:env[k] for k in expected}==expected; src=(ROOT/'scripts/run_cn_program_base_event_tier_a_report_only_holdout_v1.py').read_text(encoding='utf-8-sig'); assert "env=_label_builder_env(8)" in src
def test_generic_sidecar_validators_accept_positive_holdout_reads(tmp_path:Path):
 split='f'*64; field=tmp_path/'field'; label=tmp_path/'label'; field.mkdir(); label.mkdir(); fm={'status':'TIME_MAJOR_LAYOUT_PARITY_PASS','evaluation_role':'holdout','data_role':'holdout_report_only','split_manifest_hash':split,'validation_reads':0,'holdout_reads':2,'forward_2026_reads':0,'feedback_write':'FORBIDDEN','scheduler_write':'FORBIDDEN','archive_write':'FORBIDDEN','promotion':'FORBIDDEN','fields':['open','close'],'shards':[]}; lm={'status':'GLOBAL_SYMBOL_CONTINUITY_LABEL_SIDECARS_READY','evaluation_role':'holdout','data_role':'holdout_report_only','split_manifest_hash':split,'validation_reads':0,'holdout_reads':2,'forward_2026_reads':0}; (field/'CN_DEVELOPMENT_TIME_MAJOR_EXECUTION_LAYOUT_V2.json').write_text(json.dumps(fm),encoding='utf-8'); (label/'CN_FORWARD_LABEL_SIDECAR_MANIFEST.json').write_text(json.dumps(lm),encoding='utf-8'); replay._validate_sidecar(field,evaluation_role='holdout',split_hash=split); replay._validate_label_sidecar(label,evaluation_role='holdout',split_hash=split); fm['holdout_reads']=0; lm['holdout_reads']=0; (field/'CN_DEVELOPMENT_TIME_MAJOR_EXECUTION_LAYOUT_V2.json').write_text(json.dumps(fm),encoding='utf-8'); (label/'CN_FORWARD_LABEL_SIDECAR_MANIFEST.json').write_text(json.dumps(lm),encoding='utf-8');
 with pytest.raises(RuntimeError,match='no holdout reads'): replay._validate_sidecar(field,evaluation_role='holdout',split_hash=split)
 with pytest.raises(RuntimeError,match='no holdout reads'): replay._validate_label_sidecar(label,evaluation_role='holdout',split_hash=split)
def test_generic_session_authority_verifier_is_role_parameterized():
 src=(ROOT/'scripts/verify_cn_report_only_session_authority.py').read_text(encoding='utf-8-sig'); assert "evaluation_role:str" in src; assert "f'{prefix}_session_authority_manifest.json'" in src; assert "f'{evaluation_role}_reads'" in src; assert "--evaluation-role" in src
def test_holdout_authorization_binds_final_plan_and_report_only_boundary(tmp_path:Path):
 x=auth_builder.build(ROOT); assert x['status']=='BASE_EVENT_TIER_A_REPORT_ONLY_HOLDOUT_AUTHORIZED_NOT_RUN'; assert x['evaluation_role']=='holdout' and x['usage']=='REPORT_ONLY_CANDIDATE_TRANSFER'; assert x['resource_contract']=={'profile':'VALIDATION_DUAL_8','cpu_threads':8,'evaluator_workers':2,'candidate_count':2}; assert x['oos_authority']=='HOLDOUT_REPORT_ONLY_EVIDENCE_ONLY'; assert x['promotion_authorized'] is False and x['automatic_successor_authorized'] is False; assert x['implementation']['generic_replay_validator_sha256']; assert x['implementation']['forward_label_builder_sha256']; p=tmp_path/'auth.json';p.write_text(json.dumps(x,sort_keys=True),encoding='utf-8'); y=runtime.verify_authorization(p,repo_root=ROOT); assert y['authorization_payload_sha256']==x['authorization_payload_sha256']
def test_holdout_recovery_authorization_is_retry_only_and_incident_bound(tmp_path:Path):
 incident=json.loads((ROOT/'runtime/run_plans/cn_program_base_event_tier_a_holdout_recovery_incident_20260823.json').read_text(encoding='utf-8-sig')); x=recovery_auth_builder.build(ROOT); assert x['schema_version']==runtime.RECOVERY_AUTHORIZATION_SCHEMA; assert x['status']=='BASE_EVENT_TIER_A_REPORT_ONLY_HOLDOUT_RECOVERY_AUTHORIZED_NOT_RUN'; assert x['permitted_project_control_actions']==[ACTION_RETRY]; assert x['recovery_incident']['payload_sha256']==incident['incident_payload_sha256']; assert incident['root_cause_assessment']['status']=='REMOTE_TRACE_CONFIRMED'; assert incident['root_cause_assessment']['confirmed_error']=='thread environment is not frozen'; assert incident['fix_contract']['scope']=='PRE_EVALUATION_INFRASTRUCTURE_COMPATIBILITY_ONLY'; assert incident['recovery_preflight_assessment']['status']=='REMOTE_TRACE_CONFIRMED_ON_RETRY1'; assert incident['retry1_failure_assessment']['confirmed_error']=='holdout field sidecar drift: holdout_reads'; assert x['recovery_contract']['recovery_kind']=='INFRASTRUCTURE_PRE_EVALUATION_RETRY_FAILURE'; assert x['recovery_contract']['failed_target_run_id']=='cn_program_base_event_tier_a_report_only_holdout_retry1_20260823_5a04996'; assert x['recovery_contract']['recovery_scope']=='PRE_EVALUATION_INFRASTRUCTURE_COMPATIBILITY_ONLY'; assert x['recovery_contract']['failed_admission_file_sha256']=='937a868f164b6cee132b677310cac1347d420f07571e9146a46e3c5ef7674f86'; assert x['recovery_contract']['fresh_output_root_required'] is True; assert x['implementation']['generic_replay_validator_sha256']; assert x['implementation']['forward_label_builder_sha256']; p=tmp_path/'recovery_auth.json';p.write_text(json.dumps(x,sort_keys=True),encoding='utf-8'); y=runtime.verify_authorization(p,repo_root=ROOT); assert y['authorization_payload_sha256']==x['authorization_payload_sha256']
def test_holdout_runtime_enforces_admission_action_within_authorization():
 src=(ROOT/'src/our_system_phase2/runtime/cn_program_base_event_tier_a_report_only_holdout_v1.py').read_text(encoding='utf-8-sig'); assert "admission action is outside campaign authorization" in src
